const SUPABASE_URL = 'https://lgsmiqnvqzbvrxojhejg.supabase.co';
const SUPABASE_ANON_KEY =
	'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxnc21pcW52cXpidnJ4b2poZWpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkzNzE2MjMsImV4cCI6MjA5NDk0NzYyM30.q_CLJAqfRfH1iFbCtMD1IO-lAFaZmNs6ad8wSPQVlQM';

